name: 🐛 Bug report
description: Create a report to help us fix something
title: "[BUG]: <title>"
labels: ['bug', 'untriaged']
body:
  - type: markdown
    attributes:
      value: |
        Before filing, check if this issue already exists. For usage questions, use [discussions](https://github.com/WLAN-Pi/feedback/discussions) instead.
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: What did you expect to happen instead?
      placeholder: Describe the bug and what you expected.
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      placeholder: "1. ...\n2. ...\n3. ..."
    validations:
      required: true
  - type: input
    attributes:
      label: Version
      description: WLAN Pi OS version, package version, or any other relevant version reference.
      placeholder: e.g. 2.3.1
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Optional but very helpful.
      render: shell
    validations:
      required: false
