name: 🐛 Bug report
description: Create a report to help us fix something
title: "[BUG]: <title>"
labels: ['bug, untriaged']
body:
  - type: markdown
    attributes:
      value: |
        ## Please help us help you!

        Thank you for taking the time to fill out this bug report!

        **The GitHub issue tracker is not a support forum**. If you are not sure whether the issue could be your mistakes, ask in the [GitHub discussions](https://github.com/WLAN-Pi/feedback/discussions) first. The quickest way to verify whether it's a WLAN Pi problem is through **reproduction**.

        Make the bug obvious. Ideally, we should be able to understand the issue without running any code.
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: What did you expect?
      placeholder: Tell us what happened and what you expected instead.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      value: 
      render: shell
    validations:
      required: true
  - type: dropdown
    attributes:
      label: How often does this bug happen?
      description: |
        Following the repro steps above, how easily are you able to reproduce this bug?
      options:
        - Every time
        - Often
        - Sometimes
        - Only once
    validations:
      required: true
  - type: input
    attributes:
      label: What version are you using?
      description: |
        Please provide the version of software where this issue occurred.
    validations:
      required: true
  - type: input
    attributes:
      label: Where is the bug located?
      description: |
        If known, please provide a link to where you think the bug exists in the code.
    validations:
      required: false
  - type: checkboxes
    attributes:
      label: Self Service
      description: |
        If you feel like you could contribute to this issue, please check the box below. This would tell us and other people looking for contributions that someone is working on it.
        
        If you do check this box, please send a pull request in the next week or two so we can still delegate this to someone else if you do not submit one.
      options:
        - label: I would be willing to fix this bug myself.
  - type: checkboxes
    id: contribs
    attributes:
      label: Guidelines and Policies
      description: Please review our [contributing guidelines and policies](https://github.com/WLAN-Pi/.github/blob/main/docs/contributing.md), [code of conduct](https://github.com/WLAN-Pi/.github/blob/main/docs/code_of_conduct.md), and [disclaimer](https://github.com/WLAN-Pi/.github/blob/main/docs/disclaimer.md) before contributing.
      options:
        - label: I have read the contributing guidelines and agree to follow the code of conduct and contribution policies.
          required: true