name: 💡 Feature request
description: Create a feature request
title: "[FEATURE]: <title>"
labels: ['feature, untriaged']
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out this feature or enhancement request!
  - type: textarea
    id: feature
    attributes:
      label: What is the feature?
      description: What do you want this feature to do?
      placeholder: Tell us what you think could be enhanced and why.
    validations:
      required: true
  - type: checkboxes
    id: contribs
    attributes:
      label: Guidelines and Policies
      description: Please review our [contributing guidelines and policies](https://github.com/WLAN-Pi/.github/blob/main/docs/contributing.md), [code of conduct](https://github.com/WLAN-Pi/.github/blob/main/docs/code_of_conduct.md), and [disclaimer](https://github.com/WLAN-Pi/.github/blob/main/docs/disclaimer.md) before contributing.
      options:
        - label: I have read the contributing guidelines and agree to follow the code of conduct and contribution policies.
          required: true