name: 💡 Feature request
description: Suggest an idea or enhancement
title: "[FEATURE]: <title>"
labels: ['feature', 'untriaged']
body:
  - type: textarea
    id: feature
    attributes:
      label: What would you like?
      placeholder: Describe the feature and what problem it solves.
    validations:
      required: true