name: 📚 Documentation
description: Report a documentation issue or request an improvement
title: "[DOCS]: <title>"
labels: ['documentation', 'untriaged']
body:
  - type: textarea
    attributes:
      label: What needs to be updated?
      description: Link to the relevant doc if you can.
    validations:
      required: true
