blank_issues_enabled: false
contact_links:
  - name: 
  - name: 🤔 Questions and help
    url: https://github.com/orgs/WLAN-Pi/discussions
    about: This issue tracker is not for support questions. Please use the WLAN Pi discussions page instead.